import XCTest
@testable import ResAICore

final class ClipboardHistoryPolicyTests: XCTestCase {
    func testSensitiveAndTransientContentIsExcluded() {
        for name in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"] {
            XCTAssertFalse(ClipboardHistoryPolicy.shouldStore(text: "secret", typeNames: [name]))
        }
    }

    func testWhitespaceIsAllowedWithoutChangingOriginalAndOversizedItemsAreSkipped() {
        XCTAssertTrue(ClipboardHistoryPolicy.shouldStore(text: "  line\r\n", typeNames: []))
        XCTAssertFalse(ClipboardHistoryPolicy.shouldStore(text: " \n", typeNames: []))
        XCTAssertFalse(ClipboardHistoryPolicy.shouldStore(text: String(repeating: "x", count: 20_001), typeNames: []))
    }

    func testRetentionBoundary() {
        let now = Date(timeIntervalSince1970: 1_000_000)
        XCTAssertTrue(ClipboardHistoryPolicy.isRetained(copiedAt: now, now: now))
        XCTAssertTrue(ClipboardHistoryPolicy.isRetained(copiedAt: now.addingTimeInterval(-604800), now: now))
        XCTAssertFalse(ClipboardHistoryPolicy.isRetained(copiedAt: now.addingTimeInterval(-604801), now: now))
        XCTAssertFalse(ClipboardHistoryPolicy.isRetained(copiedAt: now.addingTimeInterval(1), now: now))
    }
}
