import Foundation

public enum ClipboardHistoryPolicy {
    public static let maxCharacters = 20_000
    public static let retention: TimeInterval = 7 * 24 * 60 * 60

    public static func shouldStore(text: String, typeNames: [String]) -> Bool {
        let excluded = ["org.nspasteboard.concealedtype", "org.nspasteboard.transienttype",
                        "org.nspasteboard.autogeneratedtype", "com.agilebits.onepassword"]
        guard !typeNames.contains(where: { name in
            excluded.contains(where: { name.lowercased().contains($0) })
        }) else { return false }
        return !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            && text.count <= maxCharacters
    }

    public static func isRetained(copiedAt: Date, now: Date = Date()) -> Bool {
        now.timeIntervalSince(copiedAt) >= 0 && now.timeIntervalSince(copiedAt) <= retention
    }
}
